name: student_app
description: Student mobile application for CEC Connect.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  pdf: ^3.11.0
  permission_handler: ^11.3.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
